# Generated by Django 6.1.1 on 2026-09-15 13:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pesquisas', '0009_user_directory_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('iniciativa', models.CharField(choices=[('EMPRESA', 'Iniciativa da empresa'), ('COLABORADOR', 'Iniciativa do colaborador')], max_length=12)),
                ('link_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios_desligamento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'formulário de desligamento',
                'verbose_name_plural': 'formulários de desligamento',
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.CreateModel(
            name='Desligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciativa', models.CharField(choices=[('EMPRESA', 'Iniciativa da empresa'), ('COLABORADOR', 'Iniciativa do colaborador')], max_length=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('AGUARDANDO_RESPOSTA', 'Aguardando resposta'), ('RESPONDIDO', 'Respondido')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desligamentos', to='pesquisas.colaborador')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desligamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desligamentos', to='desligamentos.formulariodesligamento')),
            ],
            options={
                'ordering': ('-data_criacao',),
            },
        ),
        migrations.CreateModel(
            name='PerguntaDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.TextField()),
                ('tipo_resposta', models.CharField(choices=[('TEXTO', 'Texto'), ('NOTA_0_10', 'Nota de 0 a 10'), ('RADIO', 'Múltipla escolha (escolha única)'), ('CHECKBOX', 'Caixa de seleção (múltipla escolha)')], max_length=10)),
                ('ordem', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='desligamentos.formulariodesligamento')),
            ],
            options={
                'ordering': ('ordem', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='desligamentos.perguntadesligamento')),
            ],
            options={
                'ordering': ('ordem', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RespostaDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hash_documento_respondente', models.CharField(editable=False, max_length=64)),
                ('desligamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resposta', to='desligamentos.desligamento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalheRespostaDesligamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_inteiro', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('opcoes', models.ManyToManyField(blank=True, related_name='detalhes', to='desligamentos.opcaopergunta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='desligamentos.perguntadesligamento')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='desligamentos.respostadesligamento')),
            ],
        ),
        migrations.AddConstraint(
            model_name='desligamento',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('PENDENTE', 'AGUARDANDO_RESPOSTA'))), fields=('colaborador',), name='desligamento_unico_em_aberto_por_colaborador'),
        ),
        migrations.AddConstraint(
            model_name='perguntadesligamento',
            constraint=models.UniqueConstraint(fields=('formulario', 'ordem'), name='pergunta_desligamento_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='opcaopergunta',
            constraint=models.UniqueConstraint(fields=('pergunta', 'ordem'), name='opcao_pergunta_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='detalherespostadesligamento',
            constraint=models.UniqueConstraint(fields=('resposta', 'pergunta'), name='uma_resposta_desligamento_por_pergunta'),
        ),
    ]
