# Generated by Django 6.1.1 on 2026-09-16 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desligamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desligamento',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desligamentos', to='desligamentos.formulariodesligamento'),
        ),
    ]
