# Generated by Django 6.1.1 on 2026-09-09 13:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pesquisas.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[pesquisas.models.validar_cpf])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('link_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesquisas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-data_inicio',),
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.TextField()),
                ('tipo_resposta', models.CharField(choices=[('TEXTO', 'Texto'), ('NOTA_0_10', 'Nota de 0 a 10')], max_length=12)),
                ('ordem', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='pesquisas.pesquisa')),
            ],
            options={
                'ordering': ('ordem', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RespostaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_resposta', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hash_cpf_respondente', models.CharField(editable=False, max_length=64)),
                ('pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='pesquisas.pesquisa')),
            ],
            options={
                'ordering': ('-data_resposta',),
            },
        ),
        migrations.CreateModel(
            name='DetalheResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_inteiro', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes', to='pesquisas.pergunta')),
                ('resposta_pesquisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='pesquisas.respostapesquisa')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pergunta',
            constraint=models.UniqueConstraint(fields=('pesquisa', 'ordem'), name='pergunta_ordem_unica'),
        ),
        migrations.AddConstraint(
            model_name='respostapesquisa',
            constraint=models.UniqueConstraint(fields=('pesquisa', 'hash_cpf_respondente'), name='resposta_unica_por_cpf_e_pesquisa'),
        ),
        migrations.AddConstraint(
            model_name='detalheresposta',
            constraint=models.UniqueConstraint(fields=('resposta_pesquisa', 'pergunta'), name='uma_resposta_por_pergunta'),
        ),
        migrations.AddConstraint(
            model_name='detalheresposta',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('valor_inteiro__isnull', True), ('valor_texto__isnull', False)), models.Q(('valor_inteiro__isnull', False), ('valor_texto__isnull', True)), _connector='OR'), name='detalhe_exatamente_um_valor'),
        ),
    ]
