# Generated by Django 6.1.1 on 2026-09-09 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respostapesquisa',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='pesquisas.pesquisa'),
        ),
    ]
