# Generated by Django 6.1.1 on 2026-09-09 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0002_alter_respostapesquisa_pesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalheresposta',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='pesquisas.pergunta'),
        ),
    ]
