# Generated by Django 6.1.1 on 2026-09-09 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0003_alter_detalheresposta_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_inativacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
