# Generated by Django 6.1.1 on 2026-09-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0004_colaborador_data_criacao_colaborador_data_inativacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_ativacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
