# Generated by Django 6.1.1 on 2026-09-11 13:57

import pesquisas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0006_empresa_colaborador_empresa'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='respostapesquisa',
            name='resposta_unica_por_cpf_e_pesquisa',
        ),
        migrations.RenameField(
            model_name='respostapesquisa',
            old_name='hash_cpf_respondente',
            new_name='hash_documento_respondente',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cpf',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='documento',
            field=models.CharField(default='', max_length=14, unique=True, validators=[pesquisas.models.validar_documento]),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='respostapesquisa',
            constraint=models.UniqueConstraint(fields=('pesquisa', 'hash_documento_respondente'), name='resposta_unica_por_documento_e_pesquisa'),
        ),
    ]
