# Generated by Django 6.1.1 on 2026-09-11 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisas', '0007_remove_respostapesquisa_resposta_unica_por_cpf_e_pesquisa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaborador', to=settings.AUTH_USER_MODEL),
        ),
    ]
