# Generated by Django 6.1.1 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pesquisas', '0008_colaborador_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_source',
            field=models.CharField(choices=[('LOCAL', 'Senha local'), ('DIRECTORY', 'Active Directory')], default='LOCAL', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='directory_guid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
